spring:
  # 数据源  cl-manage
  datasource:
    url: jdbc:mysql://localhost:3306/studio-dev?characterEncoding=utf-8&serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/zhifengv0.2-dev?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456

# sm2公钥、密钥，注释后即可关闭sm2功能
sm2:
  publicKey: 04171cc684596a7fd7dd26ea34ed5a7ea84b8ac124ed8e53432da4a0d1b287adbaea1f320a6db4763190dae57587ea8adf1f4254a250653b419dc64d2df9067d97
  privateKey: 410ed06116014ad4460d2018069d94debeef593fd0e3bdc3d57ab8a84f8125e2


# 备份资源和数据库sql
backup:
  sql:
    dataBackupPath: D:\upload
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    dataBaseName: studio-dev
    filename: studio
  static:
    folder: D:\upload
    zipFile: D:\upload\static.zip

